from __future__ import annotations

RANDOM_TEACHER_TRACK = "random_teacher"
SINGLE_AR_TRACK = "single_ar"
MQAR_TRACK = "mqar"
TRACKS = (RANDOM_TEACHER_TRACK, SINGLE_AR_TRACK, MQAR_TRACK)
DEFAULT_TRACK = RANDOM_TEACHER_TRACK
